### ISSUE TITLE
Unit info panel needs filling and styling

### ISSUE THREAD

**Issue by PeekabooSteam** [Pax1601/DCSOlympus#127]
This doesn't match the Figma design.

![Image](https://user-images.githubusercontent.com/66554898/227030893-3ae993ec-e16f-4d54-9066-bd3624989717.png)

Figma:

![Image](https://user-images.githubusercontent.com/66554898/227031041-9c753046-7bb3-4b19-91a4-9b5100fe2fec.png)

**Comment by ArtificialDogma** [comment]
Looks to be correct to the latest design (23/04) closing.
