### ISSUE TITLE
Cloned units spawn at current altitude and speed of original unit

### ISSUE THREAD

**Issue by PeekabooSteam** [Pax1601/DCSOlympus#150]
GIVEN I have "copied" a unit
WHEN I paste the unit
THEN the newly-pasted unit spawns at the same altitude and speed of the source unit at the time of pasting
AND the newly-pasted unit takes on the same waypoints as the source unit
BUT the new waypoints are offset from the source unit's waypoints by the offset at pasting

**Comment by Pax1601** [comment]
Duplicare
