### ISSUE TITLE
Style dropdown scrollbars

### ISSUE THREAD

**Issue by Pax1601** [Pax1601/DCSOlympus#186]
![immagine](https://user-images.githubusercontent.com/7738284/231235304-00939113-ffb8-4bd6-915d-ac76fc26a60a.png)

**Comment by Pax1601** [comment]
@ArtificialDogma can you provide a style guideline for dropdowns?

**Comment by ArtificialDogma** [comment]
@Pax1601 Older UI, but has a styled scrollbar for your reference. Should be roughly 6px wide, #FFF, rounded tips, no background colour.
![image](https://user-images.githubusercontent.com/103559271/235346782-4dc38acb-3dcd-4789-9bf7-ef867f12a736.png)
