### ISSUE TITLE
Unit spawning in in-game map only and centre map on load

### ISSUE THREAD

**Issue by PeekabooSteam** [Pax1601/DCSOlympus#20]
When the server is running, you can spawn planes anywhere in the world.  Not only is this pointless, it's taking up resources on the server and will skew the stats.  We don't want this.

Ensure unit spawning stays within the boundary of the map in the game.

While it's possible to spawn units off of the map and so on, they're currently ignoring waypoints and just flying north.  We can revisit off-map spawns in the future.

## Acceptance Criteria
1. I cannot spawn units outside of the map
2. On loading of the application, my view is centred to the centre of the server map

**Comment by Pax1601** [comment]
Partially implemented, point 1 not necessary as units spawned outside limits are valid
