### ISSUE TITLE
Finalise logo

### ISSUE THREAD

**Issue by ArtificialDogma** [Pax1601/DCSOlympus#23]
Dogma to finalise logo designs and share for feedback and voting.

**Comment by ArtificialDogma** [comment]
Logo complete - files attached:

- PNG (4k)
- PNG Flat (4k)
- SVG (Vector)

![Image](https://user-images.githubusercontent.com/103559271/220864010-437e870e-3878-41ef-a653-f93b4087af72.svg)
![Image](https://user-images.githubusercontent.com/103559271/220864012-799bd391-5b21-4900-b5a7-b4dd1e02d08b.png)
![Image](https://user-images.githubusercontent.com/103559271/220864011-0cb85538-5129-4c52-a4e2-b8d6196c1a34.png)

**Comment by Pax1601** [comment]
Looks amazing!
