### ISSUE TITLE
Fix for overlapping dropdowns

### ISSUE THREAD

**Issue by ArtificialDogma** [Pax1601/DCSOlympus#247]
When selecting a dropdown with a dropdown already open, it does not close the previous dropdown, causing overlapping in some cases. Example screenshot below.

It's hard to see, but the line titled "Howitzer" is actually from the dropdown at the top, and is appearing underneath the one already opened at the bottom

![Image](https://user-images.githubusercontent.com/103559271/235455834-bca64acf-6a57-4b90-8a66-83f2d1fdce78.png)

**Comment by Pax1601** [comment]
Duplicate
