### ISSUE TITLE
windowed client is messed up

### ISSUE THREAD

**Issue by doz8ball** [Pax1601/DCSOlympus#386]
<img width="610" alt="image" src="https://github.com/Pax1601/DCSOlympus/assets/91024799/2286a1e7-8e69-4c20-a288-a45520a48c01">
<img width="960" alt="image" src="https://github.com/Pax1601/DCSOlympus/assets/91024799/099c8002-e74b-4c8f-be74-37c5ed8f8222">

**Comment by Pax1601** [comment]
Requires some fluid styling to fix, maybe using @media in css?

**Comment by Pax1601** [comment]
Fixed as above
