### ISSUE TITLE
Ammo trucks

### ISSUE THREAD

**Issue by doz8ball** [Pax1601/DCSOlympus#389]
Units that can resupply ammo need to be labelled as such. I dont know what the fuck a Ural-4320T does

**Comment by Pax1601** [comment]
May be worth adding this info in the tips plugin? @PeekabooSteam

**Comment by PeekabooSteam** [comment]
This isn't really a control, like CTRL-click.  I was thinking of something similar a while ago.  https://github.com/users/Pax1601/projects/2?pane=issue&itemId=19075117

**Comment by Pax1601** [comment]
Maybe some sort of "keyword"?

**Comment by PeekabooSteam** [comment]
I think we could add metadata via the editor you built and use that.

**Comment by Pax1601** [comment]
Duplicate
