### ISSUE TITLE
Unknown units have no icons

### ISSUE THREAD

**Issue by PeekabooSteam** [Pax1601/DCSOlympus#528]
![Image](https://github.com/Pax1601/DCSOlympus/assets/66554898/8f49cc56-3781-4c29-8bfa-28ccf1e08397)

We need to have a generic icon - and possibly a way for people to set their own?

**Comment by Pax1601** [comment]
Agreed on the generic icon, they already have the possibility of setting their own, using the database manager

**Comment by bobprofisker** [comment]
Changed the title of this to more accurately reflect the problem as it happens for DCS units that aren't mods if they are unknown to Olympus, suggest default icon is the way to go or it just looks broken.
