### ISSUE TITLE
Mark air unit as RTB

### ISSUE THREAD

**Issue by PeekabooSteam** [Pax1601/DCSOlympus#53]
## User Story
As a GCI
I want to mark an air unit as RTB
So that I can easily see which units are still available to engage.

Note: this is putting an icon on their screen badge to _indicate_ they're RTB-ing, not to send the order to RTB.

## Acceptance Criteria

- Unit can be marked as RTB
- Unit can be unmarked as RTB

**Comment by Pax1601** [comment]
Functionality provided by "Land here" command
