### ISSUE TITLE
IADS Zone will spawn units dangling off of buildings in cities

### ISSUE THREAD

**Issue by WirtsLegs** [Pax1601/DCSOlympus#554]
Suggest testing with a small search for statics at intended spawn location, if location blocked use [getClosestPointOnRoads()](https://wiki.hoggitworld.com/view/DCS_func_getClosestPointOnRoads) and spawn there.

for larger sites it may be more complicated

**Comment by WirtsLegs** [comment]
update: just found issue 550, related/same thing

**Comment by Pax1601** [comment]
Duplicate of #550
