### ISSUE TITLE
Update spawn menu UI

### ISSUE THREAD

**Issue by ArtificialDogma** [Pax1601/DCSOlympus#610]
Update spawn menu with the following:

- [x] Change the dropdowns to appear only when relevant. For example, you cannot change the unit type before you have selected a role. Do not display dropdowns that cannot be interacted with until they can be.
- [x] Update titles on dropdowns to be "Role" and "Type" with loadout loading an option by default (current functionality).
- [x] Add spawn altitude back into the main options above the loadout information. Noted from playtesting that having to open the additional options menu every time was adding additional clicks and reduced ease of use.
- [ ] Update styling of dropdowns
- [ ] Show the disabled state of the Deploy Unit button until the unit can be deployed. 

**Screenshots below.**

![Image](https://github.com/Pax1601/DCSOlympus/assets/103559271/524e7859-3676-49a7-a90f-1e7d9e47879c)

![Image](https://github.com/Pax1601/DCSOlympus/assets/103559271/978a83cd-c9d7-4a12-8112-d928be596bf1)

![Image](https://github.com/Pax1601/DCSOlympus/assets/103559271/883e1991-0b63-419a-89ba-b11ede6bf9bf)

![Image](https://github.com/Pax1601/DCSOlympus/assets/103559271/60ff35d7-1c0f-4e37-8275-9cf58c470d14)

![Image](https://github.com/Pax1601/DCSOlympus/assets/103559271/784c520a-d780-45be-80bf-9246b642f338)

**Comment by Pax1601** [comment]
The dropdowns styling will be fixed by #609
