### ISSUE TITLE
Not all editor placed AI displaying correctly

### ISSUE THREAD

**Issue by WirtsLegs** [Pax1601/DCSOlympus#649]
See pic, a 2-ship of Mig-29As, the first one displays correctly as red with "M29" in the box, the second shows up neutral with nothing written in the box, selecting it and checking its info panel shows the correct info, and it shows up red in the selection list on the left

Also seems unit name is missing on that unit

![image](https://github.com/Pax1601/DCSOlympus/assets/9490022/ea2c026d-a993-40c0-96da-9d1cd2f1e70c)
![image](https://github.com/Pax1601/DCSOlympus/assets/9490022/e89bbb4a-95ca-40f2-b4ec-0623df30cb59)

**Comment by Pax1601** [comment]
Hard to reproduce, keeping it open to see if we can understand when and why it happens
