### ISSUE TITLE
line abreast too close

### ISSUE THREAD

**Issue by doz8ball** [Pax1601/DCSOlympus#659]
Can line abreast be 4000-7000ft? makes no sense have LaB at 300ft interval

**Comment by Pax1601** [comment]
I think most people are interested in close formations? You can use the custom formation to set a larger interval

**Comment by doz8ball** [comment]
tough to predict what people will prefer, but I think if you put line abreast people will expect tac form, also LaB/box/wedge would be ones I'd choose often

**Comment by doz8ball** [comment]
also there's no LaB close formation I know of, there's the air force route formation but it's like fighting wing distance LaB

**Comment by bobprofisker** [comment]
we've agreed to do this as a toggle style thing for normal close as everyone expects and wide
