### ISSUE TITLE
Tutorial, How-to, and Trailer Videos

### ISSUE THREAD

**Issue by Pax1601** [Pax1601/DCSOlympus#72]
Closer to release, Lovo and Dogma to create tutorial and showcase videos for promotional and instructional purposes.

**Comment by bobprofisker** [comment]
Note this no longer needs to be a full blown instructional video due to the tooltips, which tell you how to drive it. Just a release video giving a 60 seconds big picture thing. Keep it simple.

**Comment by PeekabooSteam** [comment]
Streams and good design choices are replacing the need for these.

**Comment by PeekabooSteam** [comment]
Also Dogma did a great job on the trailer so we can stick a fork in it.  :)
