### ISSUE TITLE
NATO Military Map Symbols

### ISSUE THREAD

**Issue by Wawar9** [Pax1601/DCSOlympus#727]
Hi ! 

Juste a simple suggestion : use the true NATO military symbols instead of the "gaming style" symbols.

Ref : https://commons.wikimedia.org/wiki/NATO_Military_Map_Symbols

More standard, realistic, practical. 

Big thanks for the insane amout of work you've done. Cheers !

**Comment by Pax1601** [comment]
Thank you for the suggestion! The original version of Olympus did use mil-std-2525D symbology, however users reported to be confusing. Not many are familiar with it, so we want with a custom symbology. In the future we will use themes that will allow users to use custom icons if desired!
