### ISSUE TITLE
Add an error state for the installer when users entering duplicate passwords

### ISSUE THREAD

**Issue by ArtificialDogma** [Pax1601/DCSOlympus#728]
Provide an error when users try to set all passwords the same on install.

**Comment by emcek** [comment]
@ArtificialDogma I'm happy to open PR for that, but one question, what you mean by `provide error` / `error state` ? Some kind of message box or log entry?

**Comment by Pax1601** [comment]
@emcek thank you for pitching in, but we actually decided to ditch the installer due to constant problems with Windows Defender. The new version will be an archive only release with an installer script, so this issue is no longer applicable.
