### ISSUE TITLE
Login screen nomenclature

### ISSUE THREAD

**Issue by LethalsLoaded** [Pax1601/DCSOlympus#733]
In order to reduce the confusion and questions, the login screen should have updated language to provide information to the user in an obvious way.

The login screen should:
- Have `Display Name` rather than `Name` (Users think its a U/N login)
- Have `Password` rather than `Server Password` (Users put in their actual server password)
- `Incorrect Username/Password` - can't have an incorrect username. Change to `Incorrect Password`

**Comment by PeekabooSteam** [comment]
Already done.
