### ISSUE TITLE
Script error on "getPayload"

### ISSUE THREAD

**Issue by Pax1601** [Pax1601/DCSOlympus#745]
![image](https://github.com/Pax1601/DCSOlympus/assets/7738284/afe3424e-94d9-4c62-93f2-869494ed33bc)

**Comment by Ayokas** [comment]
Got the exact same error message in `dcs.log` when spawning Aircraft (E2-D) in the air.

**Comment by GeorgeBrooker** [comment]
Happens to me when loading any instant action mission in the mig29
