### ISSUE TITLE
Improve configurator for automatic Saved Games folder detection

### ISSUE THREAD

**Issue by Pax1601** [Pax1601/DCSOlympus#747]

**Comment by LethalsLoaded** [comment]
Dumping some information from Special K that might be useful for resolution.

Special K — Yesterday at 22:08
for the installation detection, you might want to check the Saved Games folder and traverse that and search for DCS installations in there. then ask the user into which folder they want to install
I will dump you some python code, that you might want to adopt:
a) How to detect the Saved Games folder
Well, some people move that around. You can not really expect it to be at the "right" place nor being it named Saved Games. That said, this is how I do it:

```python
SAVED_GAMES = os.path.expandvars(os.path.join('%USERPROFILE%', 'Saved Games'))
if not os.path.exists(SAVED_GAMES) and sys.platform == 'win32':
    SAVED_GAMES = winreg.QueryValueEx(
        winreg.OpenKey(winreg.HKEY_CURRENT_USER,
                       r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders", 0),
        '{4C5C32FF-BB9D-43b0-B5B4-2D72E54EAAA4}'
    )[0]
```
b) Detecting DCS instances
You need to select one of the specific files. I took the serverSettings.lua, you might want to take something else. As you have a server-only mod, serverSettings.lua might do it already:
```python
    for dirname in os.listdir(SAVED_GAMES):
        if os.path.isdir(os.path.join(SAVED_GAMES, dirname)):
            path = os.path.join(SAVED_GAMES, dirname, 'Config', 'serverSettings.lua')
            if os.path.exists(path):
              # here we go
```

yes, could be nicer but you get the idea.
Then build a list out of that and let the user decide (multi-select enabled!)
A proper DCS installation writes some stuff in the registry. But I gave up using that, as people move stuff around and especially with servers and multiple instances. We do that for VAICOM Pro, as people use that on their clients, but you should be good with the above
