### ISSUE TITLE
How to connect to DCS dedicated server?

### ISSUE THREAD

**Issue by CC1337** [Pax1601/DCSOlympus#750]
Hi,

I am new to DCS dedicated server and DCS Olympus n00b - so it can be OSI 8 issue, but I have no idea where to start debugging now.

My setup:
* Windows Server 2012 (German)
* started DCS dedicated server, default ports, now tested as Administrator (insecure! but ruling out permission issues for testing) and previously with netrc command. Server installed on a network drive N:, but saved games is in the default path (userdir)
* started DCS Olympus Configurator but don't really understand what to put in for the first prompt about server? Rest is default.
* started DCS Olympus Server 1.0.3 fresh install (NOT on drive N: but on C: in default path), also node just installed today. Set all PWs. 

What I see:
* DCS server is running with default game port
* Olympus running 
![grafik](https://github.com/Pax1601/DCSOlympus/assets/4866744/57cda0b0-c9bb-483e-bf76-9bf35dfece31)
* localhost:3000 shows webinterface BUT I have no idea how to log in and how to connect it to my actual server, as I did not configure the link anywhere. If there is supposed to be magic, then it is not working for me :) it says "Connecting..." forever.
![grafik](https://github.com/Pax1601/DCSOlympus/assets/4866744/e5c56b8e-6cf0-4eb4-872b-2ff306899bcf)
After reading #733 I tried any random user name and the previously set gamemaster PW.

Logs:
* there is NO Olympus_log.txt in C:\Users\Administrator\AppData\Local\Temp
* searching for the word "olympus" in dcs.log has 0 results. I'd prefer to not upload the log here but can send it via DM.

**Comment by LethalsLoaded** [comment]
As you're running this on a dedication box, your should have `*` for the first question in DCS Configurator.

The [Discord has a troubleshooting guide,](https://discord.com/channels/1068427668887969792/1185842396873900032/1185845108134903919) which can probably help you, and there's also a `community-support` channel with a lot of information, and people willing to help you.

**Comment by CC1337** [comment]
Hi, the troubleshooting section in discord helped. The link above works after joining the server via main github page link.
I did not realize that I need to install it INTO the saved games folder. This also answers the question how it can know from each other :D
I CAN CONNECT NOW! Thank you!
Will continue with the setup now but this can be closed.
