### ISSUE TITLE
local client will not connect

### ISSUE THREAD

**Issue by BeagleRonnie** [Pax1601/DCSOlympus#751]
I open DCS and start a mission and it says that Olympus connected successfully.  I then start the client and it says waiting for connection, I start the localhost in Chrome and it asks for name and password.  I put in a generic user name and when I put in the Game Admin password is says connecting and never connects.  The three different admin passwords are different and olympus is in the saved game directory in Services.  Used port the default ports on co
[dcs.log](https://github.com/Pax1601/DCSOlympus/files/13707974/dcs.log)
[Olympus_log.txt](https://github.com/Pax1601/DCSOlympus/files/13707975/Olympus_log.txt)
nfiguration

Attached files
[dcs.log](https://github.com/Pax1601/DCSOlympus/files/13707982/dcs.log)
[Olympus_log.txt](https://github.com/Pax1601/DCSOlympus/files/13707983/Olympus_log.txt)

**Comment by Pax1601** [comment]
Please join the Discord to receive configuration support, you'll find the link in the homepage of the repo
