### ISSUE TITLE
Live password changing 

### ISSUE THREAD

**Issue by WirtsLegs** [Pax1601/DCSOlympus#759]
Add ability to change the passwords live without mission reset (perhaps through the GM interface?)

**Comment by LethalsLoaded** [comment]
Perhaps adding an 'admin' password to handle instance configuration would be ideal.
You'd need to provide this password for every 'administrative' action, like changing passwords.

Admin password would only be settable via configurator.

GM should only be able to be the game master, and not server administrator capable of modifying server data.

**Comment by Pax1601** [comment]
No longer relevant with users system
