### ISSUE TITLE
Mission embedded passwords

### ISSUE THREAD

**Issue by WirtsLegs** [Pax1601/DCSOlympus#760]
Be cool if a mission could set the red/blue/gm passwords with a small bit of lua setting a global variable or something

idea being that then a mission maker/host can have a mission-specific password they can hand to whoever needs for that mission without having to hand out the configured passwords and then worry about maybe changing them later

while a mission is running with these vars set both the olympus.json configured passwords and the ones in the miz would ideally work

**Comment by Pax1601** [comment]
No longer relevant with users system
