### ISSUE TITLE
Add a few lighter F-18 loadouts

### ISSUE THREAD

**Issue by WirtsLegs** [Pax1601/DCSOlympus#768]
could use1 or 2 more default loadouts  with aim-120s and not carrying 3 bags

**Comment by Shredmetal** [comment]
Shredmetal patch 1 #753 adds lighter AA loadouts for hornet - already merged.

**Comment by Shredmetal** [comment]
Shredmetal patch 1 https://github.com/Pax1601/DCSOlympus/pull/753 adds lighter AA loadouts for hornet - already merged.
