### ISSUE TITLE
I can't access a secondary machine on my network

### ISSUE THREAD

**Issue by GrInDmEtAl** [Pax1601/DCSOlympus#777]
installed on the machine that runs server OK Olympus works perfectly I installed it in server mode but on the other network machine it doesn't connect it only appears Login but it doesn't log in it just connects the message and it doesn't come out of it in the HOST it works OK in the browser on the client network machine to access It is only on the home page, which could be,
installed everything OK in the saved games folder and etc,,.,

**Comment by GrInDmEtAl** [comment]
![imagem_2023-12-20_182811188](https://github.com/Pax1601/DCSOlympus/assets/2384546/d9d0e7a6-cca1-4b68-a510-b221f22bde53)

**Comment by Shredmetal** [comment]
Hi, please consult the [guide ](https://github.com/Pax1601/DCSOlympus/wiki) and [troubleshooting ](https://github.com/Pax1601/DCSOlympus/wiki/Setup-Troubleshooting) tips, if you still can't figure it out drop by the [discord ](https://discord.gg/yXRBDB7g) and someone may be able to help you.

**Comment by GrInDmEtAl** [comment]
i fix add Domain for 3001 port Fixed
