### ISSUE TITLE
1.0.4 RC Installer Problems

### ISSUE THREAD

**Issue by cheefbird** [Pax1601/DCSOlympus#778]
After building (see NOTE at bottom) and running the installer from the `release-candidate` branch (commit b5f1a459c274263564aaa2d5a157e1d791c001ed) I noticed some problems:

When the installer asks for the DCS Saved Games folder, it doesn't detect it and instead sets it to "\Saved Games\DCSOlympus".

![Screenshot 2023-12-20 155731](https://github.com/Pax1601/DCSOlympus/assets/8886566/9fb245ca-75ce-4af8-ab17-e269e620160f)

If you updated it to "\Saved Games\DCS.openbeta" (as you would in 1.0.3), it installs everything into that as the root.  So things like the uninstaller and client folders appear in the DCS.openbeta folder.
![Screenshot 2023-12-20 155855](https://github.com/Pax1601/DCSOlympus/assets/8886566/84e8fe5f-5db7-42b7-ae26-d1cc20cca1dd)

Finally, if you installed it to "\Saved Games\DCS.openbeta" and then run the uninstaller, it deletes the entire DCS.openbeta folder. This is likely expected, but figured I'd call it out.

NOTE: I've been following development and successfully creating installers since pre-release, and have never seen this issue. e.g.:
![Screenshot 2023-12-20 170136](https://github.com/Pax1601/DCSOlympus/assets/8886566/a77f8795-78ae-49cb-9f7a-c13c4c0e7855)

**Comment by Shredmetal** [comment]
1.0.4 is a work in progress.
