### ISSUE TITLE
error on backend port while using FPT service

### ISSUE THREAD

**Issue by Eric20050727** [Pax1601/DCSOlympus#784]
As I dont have a public IP, i use FPT service to make sure the access the DCS server on internet. But on the using of olympus, i can sucessful open the webUI of olympus(so the client port work), while the webUI have infinite connection. It might cause by the block of backend port, but i have done the FPT connection for both two ports(i choose 13000 and 13002). 
Dose the backend port support can acess by the FPT service?

**Comment by Pax1601** [comment]
@Eric20050727 there are a number of possible causes for this problem, have you tried the troubleshooting guide? I suggest you write a message on our Discord group to recieve assistance
