### ISSUE TITLE
Unit control panel unit button style to be revised and fixed

### ISSUE THREAD

**Issue by Pax1601** [Pax1601/DCSOlympus#86]
![immagine](https://user-images.githubusercontent.com/7738284/226190184-7415af79-3c2c-40af-a748-516d3c1abd96.png)

**Comment by doz8ball** [comment]
<img width="125" alt="image" src="https://user-images.githubusercontent.com/91024799/228198401-dce49cb1-c8de-4d60-a45c-b9879b0db456.png">
