### ISSUE TITLE
Unit control panel unit marker preview not working

### ISSUE THREAD

**Issue by Pax1601** [Pax1601/DCSOlympus#87]
The unit marker preview in the unit control panel is not working

**Comment by PeekabooSteam** [comment]
Please can you elaborate on "not working"?

**Comment by Pax1601** [comment]
I mean that the current unit marker preview appears to be a placeholder and does not change to reflex the selected unit.

**Comment by doz8ball** [comment]
description is unclear but believed squashed in 0.1.1
