### ISSUE TITLE
Q: install.bat / npm install

### ISSUE THREAD

**Issue by TheDelta** [Pax1601/DCSOlympus#881]
Not per se a bug but more of a question / suggestion.

The install.bat does a npm install with only dependencies, but afterwards it does again an install of some packages:

```
call npm install --omit=dev
call npm install yargs prompt-sync sha256 tcp-ping-port
```

Whats the motivation behind this? Usually the `package-lock.json` should be shipped and only the first line shoid be used (including setting the environment variable `NODE_ENV=production` before executing install)

Otherwise newer versions will be installed which could in theory break or include other side effects with the installation.

**Comment by Pax1601** [comment]
Hi there, can you point me to where you found that line?

**Comment by TheDelta** [comment]
I'm trying atm to get Olympus working on a DCS dedicated server running on linux / wine.
I found it in `DCS.openbeta\Mods\Services\Olympus\client\install.bat` and I assumed this is also what the installer executes (couldn't find the installer source)

**Comment by Pax1601** [comment]
The code you are looking at is quite outdated now. The additional npm-install line was added last second to support the configuration script which did not have a dedicated package.json.

If you are trying to port Olympus to work on Wine I strongly suggest you start from the release-candidate branch. The next version of Olympus will have a very different installation process, file structure, and general operation.

**Comment by TheDelta** [comment]
I see. Yeah I was just looking at the current installation but if this is going to be changed (and the recommended install procedure ist taken care of) then I'll close this again. thanks.
