### ISSUE TITLE
How to update dedicated servers?

### ISSUE THREAD

**Issue by Amarok73** [Pax1601/DCSOlympus#893]
Hello, 

As the release 1.0.3 is pretty old and as I assume not reflecting the changes in DCS that was applied since then, I'd like to ask how to perform the update of the dedicated server(s) without installing everything that can be downloaded from GitHub, that as I assume can cause the mess in the files?

**Comment by WirtsLegs** [comment]
we just released 1.0.4 which includes an auto-updater feature

issue closed
