### ISSUE TITLE
Incorrect task "pill"

### ISSUE THREAD

**Issue by Pax1601** [Pax1601/DCSOlympus#90]
![immagine](https://user-images.githubusercontent.com/7738284/226191185-20fc4148-f9b8-4d4b-9be5-c32612f9ea2a.png)

Does not get correctly update, plus one "pill" should not be there.

**Comment by doz8ball** [comment]
Still incorrect.
a/c set to attack says no tasks, similar for a a/c holding position

<img width="320" alt="image" src="https://user-images.githubusercontent.com/91024799/228197510-29be2759-dd1d-49e2-9fe8-6f952a51f2fc.png">
