### ISSUE TITLE
ROE and Reaction icons not correct or in correct order

### ISSUE THREAD

**Issue by ArtificialDogma** [Pax1601/DCSOlympus#98]
Icons for ROE and Reaction are not correct or in the correct order. 
Screenshot below shows the correct order - icons should be uploaded to GitHub.
![image](https://user-images.githubusercontent.com/103559271/226253449-dc8a02cd-fe80-462a-90ee-8738cb982a0f.png)

If other options or icons are needed, please post the request in the Design channel in Discord.

**Comment by PeekabooSteam** [comment]
The code has five states.  Which needs to go and which icon applies to which state?

ROEs ["Free", "Designated free", "Designated", "Return", "Hold"]
reactionsToThreat [ "None", "Passive", "Evade", "Escape", "Abort"]

**Comment by PeekabooSteam** [comment]
ROE:
Attack all
Attack target only
Defend
Hold

Reaction:
Manoeuvre and countermeasures
Countermeasures only
None

**Comment by doz8ball** [comment]
dont understand what it's supposed to be from the above conversation

**Comment by ArtificialDogma** [comment]
Issue resolved in a seperate conversation - latest version (23/04) correct order and icons as per discord discussion.
